# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.api.device_types_api import DeviceTypesApi  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestDeviceTypesApi(unittest.TestCase):
    """DeviceTypesApi unit test stubs"""

    def setUp(self):
        self.api = metacore_obs_api.api.device_types_api.DeviceTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getdevice_types(self):
        """Test case for getdevice_types

        Retrieves one or more device_types  # noqa: E501
        """
        pass

    def test_getdevice_types_item(self):
        """Test case for getdevice_types_item

        Retrieves a device-types document  # noqa: E501
        """
        pass

    def test_patchdevice_types_item(self):
        """Test case for patchdevice_types_item

        Updates a device-types document  # noqa: E501
        """
        pass

    def test_postdevice_types(self):
        """Test case for postdevice_types

        Stores one or more device_types.  # noqa: E501
        """
        pass

    def test_putdevice_types_item(self):
        """Test case for putdevice_types_item

        Replaces a device-types document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
