# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.api.roles_api import RolesApi  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = metacore_obs_api.api.roles_api.RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getroles(self):
        """Test case for getroles

        Retrieves one or more roles  # noqa: E501
        """
        pass

    def test_getroles_item(self):
        """Test case for getroles_item

        Retrieves a roles document  # noqa: E501
        """
        pass

    def test_patchroles_item(self):
        """Test case for patchroles_item

        Updates a roles document  # noqa: E501
        """
        pass

    def test_postroles(self):
        """Test case for postroles

        Stores one or more roles.  # noqa: E501
        """
        pass

    def test_putroles_item(self):
        """Test case for putroles_item

        Replaces a roles document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
