# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.api.organization_details_api import OrganizationDetailsApi  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestOrganizationDetailsApi(unittest.TestCase):
    """OrganizationDetailsApi unit test stubs"""

    def setUp(self):
        self.api = metacore_obs_api.api.organization_details_api.OrganizationDetailsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getorg_details(self):
        """Test case for getorg_details

        Retrieves one or more org_details  # noqa: E501
        """
        pass

    def test_getorganization_details_item(self):
        """Test case for getorganization_details_item

        Retrieves a organization-details document  # noqa: E501
        """
        pass

    def test_patchorganization_details_item(self):
        """Test case for patchorganization_details_item

        Updates a organization-details document  # noqa: E501
        """
        pass

    def test_postorg_details(self):
        """Test case for postorg_details

        Stores one or more org_details.  # noqa: E501
        """
        pass

    def test_putorganization_details_item(self):
        """Test case for putorganization_details_item

        Replaces a organization-details document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
