# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.api.users_api import UsersApi  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = metacore_obs_api.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getusers(self):
        """Test case for getusers

        Retrieves one or more users  # noqa: E501
        """
        pass

    def test_getusers_item(self):
        """Test case for getusers_item

        Retrieves a users document  # noqa: E501
        """
        pass

    def test_patchusers_item(self):
        """Test case for patchusers_item

        Updates a users document  # noqa: E501
        """
        pass

    def test_postusers(self):
        """Test case for postusers

        Stores one or more users.  # noqa: E501
        """
        pass

    def test_putusers_item(self):
        """Test case for putusers_item

        Replaces a users document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
