# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.api.oplog_api import OplogApi  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestOplogApi(unittest.TestCase):
    """OplogApi unit test stubs"""

    def setUp(self):
        self.api = metacore_obs_api.api.oplog_api.OplogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_oplog_item(self):
        """Test case for get_oplog_item

        Retrieves a Oplog document  # noqa: E501
        """
        pass

    def test_getoplog(self):
        """Test case for getoplog

        Retrieves one or more oplog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
