# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.api.device_shadow_api import DeviceShadowApi  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestDeviceShadowApi(unittest.TestCase):
    """DeviceShadowApi unit test stubs"""

    def setUp(self):
        self.api = metacore_obs_api.api.device_shadow_api.DeviceShadowApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getdevice_shadow(self):
        """Test case for getdevice_shadow

        Retrieves one or more device_shadow  # noqa: E501
        """
        pass

    def test_getdevice_shadow_item(self):
        """Test case for getdevice_shadow_item

        Retrieves a device-shadow document  # noqa: E501
        """
        pass

    def test_patchdevice_shadow_item(self):
        """Test case for patchdevice_shadow_item

        Updates a device-shadow document  # noqa: E501
        """
        pass

    def test_postdevice_shadow(self):
        """Test case for postdevice_shadow

        Stores one or more device_shadow.  # noqa: E501
        """
        pass

    def test_putdevice_shadow_item(self):
        """Test case for putdevice_shadow_item

        Replaces a device-shadow document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
