# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.models.sensors import Sensors  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestSensors(unittest.TestCase):
    """Sensors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensors(self):
        """Test Sensors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metacore_obs_api.models.sensors.Sensors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
