# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.api.shown_widget_settings_api import ShownWidgetSettingsApi  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestShownWidgetSettingsApi(unittest.TestCase):
    """ShownWidgetSettingsApi unit test stubs"""

    def setUp(self):
        self.api = metacore_obs_api.api.shown_widget_settings_api.ShownWidgetSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getshown_widget_settings(self):
        """Test case for getshown_widget_settings

        Retrieves one or more shown_widget_settings  # noqa: E501
        """
        pass

    def test_getshown_widget_settings_item(self):
        """Test case for getshown_widget_settings_item

        Retrieves a shown-widget-settings document  # noqa: E501
        """
        pass

    def test_patchshown_widget_settings_item(self):
        """Test case for patchshown_widget_settings_item

        Updates a shown-widget-settings document  # noqa: E501
        """
        pass

    def test_postshown_widget_settings(self):
        """Test case for postshown_widget_settings

        Stores one or more shown_widget_settings.  # noqa: E501
        """
        pass

    def test_putshown_widget_settings_item(self):
        """Test case for putshown_widget_settings_item

        Replaces a shown-widget-settings document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
