# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.models.measurables import Measurables  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestMeasurables(unittest.TestCase):
    """Measurables unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMeasurables(self):
        """Test Measurables"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metacore_obs_api.models.measurables.Measurables()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
