# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.api.graph_settings_api import GraphSettingsApi  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestGraphSettingsApi(unittest.TestCase):
    """GraphSettingsApi unit test stubs"""

    def setUp(self):
        self.api = metacore_obs_api.api.graph_settings_api.GraphSettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getgraph_settings(self):
        """Test case for getgraph_settings

        Retrieves one or more graph_settings  # noqa: E501
        """
        pass

    def test_getgraph_settings_item(self):
        """Test case for getgraph_settings_item

        Retrieves a graph-settings document  # noqa: E501
        """
        pass

    def test_patchgraph_settings_item(self):
        """Test case for patchgraph_settings_item

        Updates a graph-settings document  # noqa: E501
        """
        pass

    def test_postgraph_settings(self):
        """Test case for postgraph_settings

        Stores one or more graph_settings.  # noqa: E501
        """
        pass

    def test_putgraph_settings_item(self):
        """Test case for putgraph_settings_item

        Replaces a graph-settings document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
