# coding: utf-8

"""
    Metacore IOT Object Storage API

    Metacore IOT Core Services  # noqa: E501

    The version of the OpenAPI document: 0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metacore_obs_api
from metacore_obs_api.api.organizations_api import OrganizationsApi  # noqa: E501
from metacore_obs_api.rest import ApiException


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = metacore_obs_api.api.organizations_api.OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getorganizations_item(self):
        """Test case for getorganizations_item

        Retrieves a organizations document  # noqa: E501
        """
        pass

    def test_getorgs(self):
        """Test case for getorgs

        Retrieves one or more orgs  # noqa: E501
        """
        pass

    def test_patchorganizations_item(self):
        """Test case for patchorganizations_item

        Updates a organizations document  # noqa: E501
        """
        pass

    def test_postorgs(self):
        """Test case for postorgs

        Stores one or more orgs.  # noqa: E501
        """
        pass

    def test_putorganizations_item(self):
        """Test case for putorganizations_item

        Replaces a organizations document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
